// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZYHUlj3UKsTfBUwN7LShGNzH8jRkAdZM',
    appId: '1:753703662633:web:a63d9310086f914bda9838',
    messagingSenderId: '753703662633',
    projectId: 'coachus-c7c54',
    authDomain: 'coachus-c7c54.firebaseapp.com',
    storageBucket: 'coachus-c7c54.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1PjbZ5RuNI9nrogqDFlm_vj9zTvDsMyY',
    appId: '1:753703662633:android:381c94d26fe40046da9838',
    messagingSenderId: '753703662633',
    projectId: 'coachus-c7c54',
    storageBucket: 'coachus-c7c54.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFbg5k0YdP4orwGOnIdSEN6l6Dn02tBeM',
    appId: '1:753703662633:ios:68f91c5cac01b2f7da9838',
    messagingSenderId: '753703662633',
    projectId: 'coachus-c7c54',
    storageBucket: 'coachus-c7c54.firebasestorage.app',
    iosBundleId: 'com.example.didpool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFbg5k0YdP4orwGOnIdSEN6l6Dn02tBeM',
    appId: '1:753703662633:ios:68f91c5cac01b2f7da9838',
    messagingSenderId: '753703662633',
    projectId: 'coachus-c7c54',
    storageBucket: 'coachus-c7c54.firebasestorage.app',
    iosBundleId: 'com.example.didpool',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZYHUlj3UKsTfBUwN7LShGNzH8jRkAdZM',
    appId: '1:753703662633:web:34c703ddb84857d0da9838',
    messagingSenderId: '753703662633',
    projectId: 'coachus-c7c54',
    authDomain: 'coachus-c7c54.firebaseapp.com',
    storageBucket: 'coachus-c7c54.firebasestorage.app',
  );

}